# [triangle, diamond]
board_type: diamond

# 4-8 for triangle, 3-6 for diamond
board_size: 4

# Must be in the format [[y, x], [y, x], ...]
# or
# - [y, x]
# - [y, x]
# - ...
open_cell_positions:
  - [1, 2]

episodes: 600

# [table, nn]
critic_type: nn

# Required if critic: nn
# Dimension of critic's NN, number of layers and neurons in each layer (e.g. (5, 10, 1) is 3 layers with 5, 10 and 1 neurons)
nn_dims: [16, 5, 1]

# Remember that it is wise to use a "much lower" learning rate for the critic when it uses a neural network
learning_rate_critic: 0.001 # 0.1 works for table, 0.001 for nn
learning_rate_actor: 0.195 # 0.1 works for table, 0.195 for table

eligibility_decay_critic: 0.85
eligibility_decay_actor: 0.85
discount_factor_critic: 0.85
discount_factor_actor: 0.85
epsilon: 1

visualize: True
# Delay between frames in milliseconds for visualization
frame_time: 1000
