# [triangle, diamond]
board_type: diamond

# 4-8 for triangle, 3-6 for diamond
board_size: 4

# Must be in the format [[y, x], [y, x], ...]
# or
# - [y, x]
# - [y, x]
# - ...
open_cell_positions:
  - [2, 1]

episodes: 100

# [table, nn]
critic_type: table

# Required if critic: nn
# Dimension of critic's NN, number of layers and neurons in each layer (e.g. (5, 10, 1) is 3 layers with 5, 10 and 1 neurons)
nn_dim: [5, 10, 1]

learning_rate_critic: 0.1
learning_rate_actor: 0.1
eligibility_decay_critic: 0.9
eligibility_decay_actor: 0.9
discount_factor_critic: 0.9
discount_factor_actor: 0.9
epsilon: 0.5

visualize: True
# Delay between frames in milliseconds for visualization
frame_time: 1000
